---
Name: 'seoextensions'
---
Page:
  extensions:
    - SeoObjectExtension
SiteConfig:
  extensions:
    - SeoSiteConfig
# Example of how to exclude extra page types from showing the SEO tab:
# SeoObjectExtension:
#   excluded_page_types:
#     - 'SomePage'

# Example of how to set content fields to be used for a page type
#NewPage:
#  SeoContent:
#    - 'ContentField1'
#    - 'ContentField2'
