---
Name: 'seoextensions'
---
Page:
  extensions:
    - 'SeoObjectExtension'
# Example of how to exclude extra page types from showing the SEO tab:
# SeoObjectExtension:
#   excluded_page_types:
<<<<<<< HEAD
#     - 'SomePage'

ProductGroupPage:
  SeoContent:
    - 'TopContent'
    - 'BottomContent'
=======
#     - 'SomePage'
>>>>>>> a5cfc3ca0ead498c35f965e5a642f35c3550c15c
