---
Name: 'seoextensions'
---
Page:
  extensions:
    - SeoObjectExtension
SiteConfig:
  extensions:
    - SeoSiteConfig
#SeoObjectExtension:
#  use_webmaster_tag: true
# Example of how to exclude extra page types from showing the SEO tab:
# SeoObjectExtension:
#   excluded_page_types:
#     - 'SomePage'

