---
Name: 'seoextensions'
---
Page:
  extensions:
    - Hubertusanton\SilverStripeSeo\SeoObjectExtension
SiteConfig:
  extensions:
    - Hubertusanton\SilverStripeSeo\SeoSiteConfig
# Example of how to exclude extra page types from showing the SEO tab:
# SeoObjectExtension:
#   excluded_page_types:
#     - 'SomePage'

